/// <mls fileReference="_102051_/l1/cafeFlow/layer_1_external/adapters/persistence/seeds.ts" enhancement="_blank"/>

// Deterministic initial data for cafeFlow. Generated by agentCbSeeds.
// Discovered by shape (TableSeedRows) from this tableDefsDir and merged into matching
// TableDefinition.seedRows. MDM rows target 102034-owned repositories through the global registry.

import type { TableSeedRows } from '/_102034_/l1/server/layer_1_external/persistence/contracts.js';

export const menuItemIngredientSeeds: TableSeedRows = {
  "seedFor": "cafeFlowMenuItemIngredient",
  "rows": [
    {
      "menu_item_ingredient_id": "58db10ca-59db-425d-86db-0da457db0f37",
      "menu_item_id": "5a4303a1-5943-420e-8843-007b5742fee8",
      "stock_item_id": "2bf5d9b8-2cf5-4b4b-8df5-dcde2ef5de71",
      "unit": "menu-item-ingredient-1",
      "created_at": "2026-07-01T08:00:00.000Z",
      "details": {
        "label": "Menu Item Ingredient 1",
        "updatedAt": "2026-07-01T08:00:00.000Z",
        "quantity": 10
      }
    },
    {
      "menu_item_ingredient_id": "95b7039b-94b7-4208-87b7-06c196b7052e",
      "menu_item_id": "b8da376c-b9da-48ff-8ada-3a92bbda3c25",
      "stock_item_id": "cd85b55d-cc85-43ca-8b85-b237ca85b0a4",
      "unit": "menu-item-ingredient-2",
      "created_at": "2026-07-01T09:00:00.000Z",
      "details": {
        "label": "Menu Item Ingredient 2",
        "updatedAt": "2026-07-01T09:00:00.000Z",
        "quantity": 3
      }
    }
  ]
};

export const orderSeeds: TableSeedRows = {
  "seedFor": "cafeFlowOrder",
  "rows": [
    {
      "order_id": "30f9adad-2ff9-4c1a-8ef9-aa872df9a8f4",
      "shift_id": "c58c7c15-c48c-4a82-838c-78efc28c775c",
      "status": "registered",
      "order_type": "dineIn",
      "created_at": "2026-07-01T08:00:00.000Z",
      "details": {
        "label": "Order 1",
        "updatedAt": "2026-07-01T08:00:00.000Z",
        "tableNumber": "table-number-1",
        "priority": true,
        "priorityReason": "priority-reason-1",
        "receivedAt": "2026-07-01T08:00:00.000Z",
        "inPreparationAt": "2026-07-01T08:00:00.000Z",
        "readyAt": "2026-07-01T08:00:00.000Z",
        "deliveredAt": "2026-07-01T08:00:00.000Z"
      }
    },
    {
      "order_id": "10a63d08-11a6-4e9b-82a6-402e13a641c1",
      "shift_id": "a3fbd6f0-a4fb-4883-85fb-da16a6fbdba9",
      "status": "registered",
      "order_type": "dineIn",
      "created_at": "2026-07-01T09:00:00.000Z",
      "details": {
        "label": "Order 2",
        "updatedAt": "2026-07-01T09:00:00.000Z",
        "tableNumber": "table-number-2",
        "priority": false,
        "priorityReason": "priority-reason-2",
        "receivedAt": "2026-07-01T09:00:00.000Z",
        "inPreparationAt": "2026-07-01T09:00:00.000Z",
        "readyAt": "2026-07-01T09:00:00.000Z",
        "deliveredAt": "2026-07-01T09:00:00.000Z"
      }
    }
  ]
};

export const shiftSeeds: TableSeedRows = {
  "seedFor": "cafeFlowShift",
  "rows": [
    {
      "shift_id": "c58c7c15-c48c-4a82-838c-78efc28c775c",
      "status": "open",
      "created_at": "2026-07-01T08:00:00.000Z",
      "details": {
        "label": "Shift 1",
        "updatedAt": "2026-07-01T08:00:00.000Z",
        "openedAt": "2026-07-01T08:00:00.000Z",
        "closedAt": "2026-07-01T08:00:00.000Z",
        "openedBy": "opened-by-1",
        "closedBy": "closed-by-1",
        "totalApurado": 12.5,
        "notes": "notes-1"
      }
    },
    {
      "shift_id": "a3fbd6f0-a4fb-4883-85fb-da16a6fbdba9",
      "status": "open",
      "created_at": "2026-07-01T09:00:00.000Z",
      "details": {
        "label": "Shift 2",
        "updatedAt": "2026-07-01T09:00:00.000Z",
        "openedAt": "2026-07-01T09:00:00.000Z",
        "closedAt": "2026-07-01T09:00:00.000Z",
        "openedBy": "opened-by-2",
        "closedBy": "closed-by-2",
        "totalApurado": 19.9,
        "notes": "notes-2"
      }
    }
  ]
};

export const shiftClosingReportSeeds: TableSeedRows = {
  "seedFor": "cafeFlowShiftClosingReport",
  "rows": [
    {
      "shift_closing_report_id": "ccc4c114-cdc4-42a7-8ec4-c43acfc4c5cd",
      "shift_id": "c58c7c15-c48c-4a82-838c-78efc28c775c",
      "created_at": "2026-07-01T08:00:00.000Z",
      "details": {
        "label": "Shift Closing Report 1",
        "updatedAt": "2026-07-01T08:00:00.000Z",
        "totalApurado": 12.5,
        "paidOrderCount": 10
      }
    },
    {
      "shift_closing_report_id": "4e2d5ae9-4d2d-4956-8c2d-57c34b2d5630",
      "shift_id": "a3fbd6f0-a4fb-4883-85fb-da16a6fbdba9",
      "created_at": "2026-07-01T09:00:00.000Z",
      "details": {
        "label": "Shift Closing Report 2",
        "updatedAt": "2026-07-01T09:00:00.000Z",
        "totalApurado": 19.9,
        "paidOrderCount": 3
      }
    }
  ]
};

export const stockAdjustmentSeeds: TableSeedRows = {
  "seedFor": "cafeFlowStockAdjustment",
  "rows": [
    {
      "stock_adjustment_id": "fb71839c-fc71-452f-8d71-86c2fe718855",
      "stock_item_id": "2bf5d9b8-2cf5-4b4b-8df5-dcde2ef5de71",
      "status": "posted",
      "created_at": "2026-07-01T08:00:00.000Z",
      "details": {
        "label": "Stock Adjustment 1",
        "updatedAt": "2026-07-01T08:00:00.000Z",
        "quantity": 10,
        "reason": "reason-1",
        "voidedAt": "2026-07-01T08:00:00.000Z",
        "voidedReason": "voided-reason-1"
      }
    },
    {
      "stock_adjustment_id": "1cd98651-1bd9-44be-8ad9-832b19d98198",
      "stock_item_id": "cd85b55d-cc85-43ca-8b85-b237ca85b0a4",
      "status": "posted",
      "created_at": "2026-07-01T09:00:00.000Z",
      "details": {
        "label": "Stock Adjustment 2",
        "updatedAt": "2026-07-01T09:00:00.000Z",
        "quantity": 3,
        "reason": "reason-2",
        "voidedAt": "2026-07-01T09:00:00.000Z",
        "voidedReason": "voided-reason-2"
      }
    }
  ]
};

export const stockConsumptionSeeds: TableSeedRows = {
  "seedFor": "cafeFlowStockConsumption",
  "rows": [
    {
      "stock_consumption_id": "ca8f3df0-cb8f-4f83-8c8f-4116cd8f42a9",
      "stock_item_id": "2bf5d9b8-2cf5-4b4b-8df5-dcde2ef5de71",
      "order_id": "30f9adad-2ff9-4c1a-8ef9-aa872df9a8f4",
      "status": "posted",
      "created_at": "2026-07-01T08:00:00.000Z",
      "details": {
        "label": "Stock Consumption 1",
        "updatedAt": "2026-07-01T08:00:00.000Z",
        "quantity": 10,
        "voidedAt": "2026-07-01T08:00:00.000Z",
        "voidReason": "void-reason-1"
      }
    },
    {
      "stock_consumption_id": "ec1fe315-eb1f-4182-8a1f-dfefe91fde5c",
      "stock_item_id": "cd85b55d-cc85-43ca-8b85-b237ca85b0a4",
      "order_id": "10a63d08-11a6-4e9b-82a6-402e13a641c1",
      "status": "posted",
      "created_at": "2026-07-01T09:00:00.000Z",
      "details": {
        "label": "Stock Consumption 2",
        "updatedAt": "2026-07-01T09:00:00.000Z",
        "quantity": 3,
        "voidedAt": "2026-07-01T09:00:00.000Z",
        "voidReason": "void-reason-2"
      }
    }
  ]
};

export const stockLevelSeeds: TableSeedRows = {
  "seedFor": "cafeFlowStockLevel",
  "rows": [
    {
      "stock_level_id": "d85dc995-d75d-4802-865d-c66fd55dc4dc",
      "stock_item_id": "2bf5d9b8-2cf5-4b4b-8df5-dcde2ef5de71",
      "unit": "stock-level-1",
      "created_at": "2026-07-01T08:00:00.000Z",
      "details": {
        "label": "Stock Level 1",
        "updatedAt": "2026-07-01T08:00:00.000Z",
        "currentQuantity": 10,
        "minimumLevel": 10,
        "lastDecrementAt": "2026-07-01T08:00:00.000Z",
        "lastAdjustmentAt": "2026-07-01T08:00:00.000Z"
      }
    },
    {
      "stock_level_id": "b6cd2470-b7cd-4603-88cd-2796b9cd2929",
      "stock_item_id": "cd85b55d-cc85-43ca-8b85-b237ca85b0a4",
      "unit": "stock-level-2",
      "created_at": "2026-07-01T09:00:00.000Z",
      "details": {
        "label": "Stock Level 2",
        "updatedAt": "2026-07-01T09:00:00.000Z",
        "currentQuantity": 3,
        "minimumLevel": 3,
        "lastDecrementAt": "2026-07-01T09:00:00.000Z",
        "lastAdjustmentAt": "2026-07-01T09:00:00.000Z"
      }
    }
  ]
};

export const mdmEntityIndexSeeds: TableSeedRows = {
  "seedFor": "mdmEntityIndex",
  "rows": [
    {
      "mdmId": "28793276-2979-4409-8679-2f50277930e3",
      "subtype": "Product",
      "name": "Menu Category 1",
      "status": "Active",
      "docType": null,
      "docId": null,
      "countryCode": "US",
      "tags": [
        "cafeFlow",
        "MenuCategory"
      ],
      "searchVector": "menu category 1 menucategory cafeflow",
      "mergedInto": null,
      "dynamoPk": "28793276-2979-4409-8679-2f50277930e3",
      "createdAt": "2026-07-01T08:00:00.000Z",
      "updatedAt": "2026-07-01T08:00:00.000Z"
    },
    {
      "mdmId": "05548e27-0454-4c94-8754-914d06548fba",
      "subtype": "Product",
      "name": "Menu Category 2",
      "status": "Active",
      "docType": null,
      "docId": null,
      "countryCode": "US",
      "tags": [
        "cafeFlow",
        "MenuCategory"
      ],
      "searchVector": "menu category 2 menucategory cafeflow",
      "mergedInto": null,
      "dynamoPk": "05548e27-0454-4c94-8754-914d06548fba",
      "createdAt": "2026-07-01T09:00:00.000Z",
      "updatedAt": "2026-07-01T09:00:00.000Z"
    },
    {
      "mdmId": "5a4303a1-5943-420e-8843-007b5742fee8",
      "subtype": "Product",
      "name": "Menu Item 1",
      "status": "Active",
      "docType": null,
      "docId": null,
      "countryCode": "US",
      "tags": [
        "cafeFlow",
        "MenuItem"
      ],
      "searchVector": "menu item 1 menuitem cafeflow",
      "mergedInto": null,
      "dynamoPk": "5a4303a1-5943-420e-8843-007b5742fee8",
      "createdAt": "2026-07-01T08:00:00.000Z",
      "updatedAt": "2026-07-01T08:00:00.000Z"
    },
    {
      "mdmId": "b8da376c-b9da-48ff-8ada-3a92bbda3c25",
      "subtype": "Product",
      "name": "Menu Item 2",
      "status": "Active",
      "docType": null,
      "docId": null,
      "countryCode": "US",
      "tags": [
        "cafeFlow",
        "MenuItem"
      ],
      "searchVector": "menu item 2 menuitem cafeflow",
      "mergedInto": null,
      "dynamoPk": "b8da376c-b9da-48ff-8ada-3a92bbda3c25",
      "createdAt": "2026-07-01T09:00:00.000Z",
      "updatedAt": "2026-07-01T09:00:00.000Z"
    },
    {
      "mdmId": "2bf5d9b8-2cf5-4b4b-8df5-dcde2ef5de71",
      "subtype": "Product",
      "name": "Stock Item 1",
      "status": "Active",
      "docType": null,
      "docId": null,
      "countryCode": "US",
      "tags": [
        "cafeFlow",
        "StockItem"
      ],
      "searchVector": "stock item 1 stockitem cafeflow",
      "mergedInto": null,
      "dynamoPk": "2bf5d9b8-2cf5-4b4b-8df5-dcde2ef5de71",
      "createdAt": "2026-07-01T08:00:00.000Z",
      "updatedAt": "2026-07-01T08:00:00.000Z"
    },
    {
      "mdmId": "cd85b55d-cc85-43ca-8b85-b237ca85b0a4",
      "subtype": "Product",
      "name": "Stock Item 2",
      "status": "Active",
      "docType": null,
      "docId": null,
      "countryCode": "US",
      "tags": [
        "cafeFlow",
        "StockItem"
      ],
      "searchVector": "stock item 2 stockitem cafeflow",
      "mergedInto": null,
      "dynamoPk": "cd85b55d-cc85-43ca-8b85-b237ca85b0a4",
      "createdAt": "2026-07-01T09:00:00.000Z",
      "updatedAt": "2026-07-01T09:00:00.000Z"
    }
  ]
};

export const mdmDocumentSeeds: TableSeedRows = {
  "seedFor": "mdmDocumentCache",
  "rows": [
    {
      "mdmId": "28793276-2979-4409-8679-2f50277930e3",
      "version": 1,
      "details": {
        "mdmId": "28793276-2979-4409-8679-2f50277930e3",
        "subtype": "Product",
        "name": "Menu Category 1",
        "status": "Active",
        "docType": null,
        "docId": null,
        "countryCode": "US",
        "tags": [
          "cafeFlow",
          "MenuCategory"
        ],
        "aliases": [],
        "contacts": [],
        "relationshipRefs": {},
        "addresses": [],
        "mergedInto": null,
        "createdAt": "2026-07-01T08:00:00.000Z",
        "updatedAt": "2026-07-01T08:00:00.000Z",
        "cafeFlow": {
          "menuCategoryId": "28793276-2979-4409-8679-2f50277930e3",
          "name": "Menu Category 1",
          "description": "Menu Category 1 description",
          "displayOrder": 10,
          "active": true,
          "createdAt": "2026-07-01T08:00:00.000Z",
          "updatedAt": "2026-07-01T08:00:00.000Z"
        }
      }
    },
    {
      "mdmId": "05548e27-0454-4c94-8754-914d06548fba",
      "version": 1,
      "details": {
        "mdmId": "05548e27-0454-4c94-8754-914d06548fba",
        "subtype": "Product",
        "name": "Menu Category 2",
        "status": "Active",
        "docType": null,
        "docId": null,
        "countryCode": "US",
        "tags": [
          "cafeFlow",
          "MenuCategory"
        ],
        "aliases": [],
        "contacts": [],
        "relationshipRefs": {},
        "addresses": [],
        "mergedInto": null,
        "createdAt": "2026-07-01T09:00:00.000Z",
        "updatedAt": "2026-07-01T09:00:00.000Z",
        "cafeFlow": {
          "menuCategoryId": "05548e27-0454-4c94-8754-914d06548fba",
          "name": "Menu Category 2",
          "description": "Menu Category 2 description",
          "displayOrder": 3,
          "active": false,
          "createdAt": "2026-07-01T09:00:00.000Z",
          "updatedAt": "2026-07-01T09:00:00.000Z"
        }
      }
    },
    {
      "mdmId": "5a4303a1-5943-420e-8843-007b5742fee8",
      "version": 1,
      "details": {
        "mdmId": "5a4303a1-5943-420e-8843-007b5742fee8",
        "subtype": "Product",
        "name": "Menu Item 1",
        "status": "Active",
        "docType": null,
        "docId": null,
        "countryCode": "US",
        "tags": [
          "cafeFlow",
          "MenuItem"
        ],
        "aliases": [],
        "contacts": [],
        "relationshipRefs": {},
        "addresses": [],
        "mergedInto": null,
        "createdAt": "2026-07-01T08:00:00.000Z",
        "updatedAt": "2026-07-01T08:00:00.000Z",
        "cafeFlow": {
          "menuItemId": "5a4303a1-5943-420e-8843-007b5742fee8",
          "name": "Menu Item 1",
          "description": "Menu Item 1 description",
          "menuCategoryId": "28793276-2979-4409-8679-2f50277930e3",
          "price": 12.5,
          "itemType": "simple",
          "status": "draft",
          "activatedAt": "2026-07-01T08:00:00.000Z",
          "inactivatedAt": "2026-07-01T08:00:00.000Z",
          "createdAt": "2026-07-01T08:00:00.000Z",
          "updatedAt": "2026-07-01T08:00:00.000Z"
        }
      }
    },
    {
      "mdmId": "b8da376c-b9da-48ff-8ada-3a92bbda3c25",
      "version": 1,
      "details": {
        "mdmId": "b8da376c-b9da-48ff-8ada-3a92bbda3c25",
        "subtype": "Product",
        "name": "Menu Item 2",
        "status": "Active",
        "docType": null,
        "docId": null,
        "countryCode": "US",
        "tags": [
          "cafeFlow",
          "MenuItem"
        ],
        "aliases": [],
        "contacts": [],
        "relationshipRefs": {},
        "addresses": [],
        "mergedInto": null,
        "createdAt": "2026-07-01T09:00:00.000Z",
        "updatedAt": "2026-07-01T09:00:00.000Z",
        "cafeFlow": {
          "menuItemId": "b8da376c-b9da-48ff-8ada-3a92bbda3c25",
          "name": "Menu Item 2",
          "description": "Menu Item 2 description",
          "menuCategoryId": "05548e27-0454-4c94-8754-914d06548fba",
          "price": 19.9,
          "itemType": "simple",
          "status": "draft",
          "activatedAt": "2026-07-01T09:00:00.000Z",
          "inactivatedAt": "2026-07-01T09:00:00.000Z",
          "createdAt": "2026-07-01T09:00:00.000Z",
          "updatedAt": "2026-07-01T09:00:00.000Z"
        }
      }
    },
    {
      "mdmId": "2bf5d9b8-2cf5-4b4b-8df5-dcde2ef5de71",
      "version": 1,
      "details": {
        "mdmId": "2bf5d9b8-2cf5-4b4b-8df5-dcde2ef5de71",
        "subtype": "Product",
        "name": "Stock Item 1",
        "status": "Active",
        "docType": null,
        "docId": null,
        "countryCode": "US",
        "tags": [
          "cafeFlow",
          "StockItem"
        ],
        "aliases": [],
        "contacts": [],
        "relationshipRefs": {},
        "addresses": [],
        "mergedInto": null,
        "createdAt": "2026-07-01T08:00:00.000Z",
        "updatedAt": "2026-07-01T08:00:00.000Z",
        "cafeFlow": {
          "stockItemId": "2bf5d9b8-2cf5-4b4b-8df5-dcde2ef5de71",
          "name": "Stock Item 1",
          "unit": "kg",
          "minimumLevel": 10,
          "createdAt": "2026-07-01T08:00:00.000Z",
          "updatedAt": "2026-07-01T08:00:00.000Z"
        }
      }
    },
    {
      "mdmId": "cd85b55d-cc85-43ca-8b85-b237ca85b0a4",
      "version": 1,
      "details": {
        "mdmId": "cd85b55d-cc85-43ca-8b85-b237ca85b0a4",
        "subtype": "Product",
        "name": "Stock Item 2",
        "status": "Active",
        "docType": null,
        "docId": null,
        "countryCode": "US",
        "tags": [
          "cafeFlow",
          "StockItem"
        ],
        "aliases": [],
        "contacts": [],
        "relationshipRefs": {},
        "addresses": [],
        "mergedInto": null,
        "createdAt": "2026-07-01T09:00:00.000Z",
        "updatedAt": "2026-07-01T09:00:00.000Z",
        "cafeFlow": {
          "stockItemId": "cd85b55d-cc85-43ca-8b85-b237ca85b0a4",
          "name": "Stock Item 2",
          "unit": "kg",
          "minimumLevel": 3,
          "createdAt": "2026-07-01T09:00:00.000Z",
          "updatedAt": "2026-07-01T09:00:00.000Z"
        }
      }
    }
  ]
};
